//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLTH.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class glth_airlines
    {
        public int airlineid { get; set; }
        public string name { get; set; }
        public string twodigitcode { get; set; }
        public string threedigitcode { get; set; }
        public string country { get; set; }
    }
}
