//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLTH.Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class glth_routes
    {
        public int routeid { get; set; }
        public string airlinetwolettercode { get; set; }
        public string origin { get; set; }
        public string destination { get; set; }
    }
}
